apiVersion: v1
kind: Service
metadata:
  name: patroni-haproxy-nodeport
  namespace: patroni
spec:
  type: NodePort
  selector:
    app: patroni-haproxy
  ports:
    - name: primary
      port: 5432      # Thay đổi từ 5000 thành 5432
      targetPort: 5432
      nodePort: 30500
    - name: replica
      port: 5433      # Thay đổi từ 5001 thành 5433
      targetPort: 5433
      nodePort: 30501
    - name: stats
      port: 8404
      targetPort: 8404
      nodePort: 30504