apiVersion: apps/v1
kind: Deployment
metadata:
  name: patroni-haproxy
  namespace: patroni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patroni-haproxy
  template:
    metadata:
      labels:
        app: patroni-haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy
          ports:
            - containerPort: 5432  # Frontend for write operations
            - containerPort: 5433  # Frontend for read operations
            - containerPort: 8404  # Stats endpoint
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
          # Add liveness and readiness probes
          livenessProbe:
            httpGet:
              path: /
              port: 8404
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8404
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: haproxy-config
          configMap:
            name: patroni-haproxy-config