apiVersion: batch/v1
kind: Job
metadata:
  name: sync-master-data-2
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: sync-master-data
          image: postgres:16
          command:
            - sh
            - -c
            - |
              for i in $(seq 1 30); do
                pg_isready -h postgresql-master -U tuan && break
                sleep 5
              done
              PGPASSWORD="20226100" pg_basebackup -h postgresql-master -D /var/lib/slave-postgresql/2/data -U tuan -vP
          volumeMounts:
            - mountPath: /var/lib/slave-postgresql/2/data
              name: postgresql-data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data-slave-2