apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-slave-0
  namespace: default
  labels:
    component: postgresql-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgresql-slave-0
  template:
    metadata:
      labels:
        component: postgresql-slave-0
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/postgresql/data/pg_log
              chown -R postgres:postgres /var/lib/postgresql/data/pg_log
              chmod 700 /var/lib/postgresql/data/pg_log
              
              echo "primary_conninfo = 'host=postgresql-master port=5432 user=tuan password=20226100 application_name=slave0'" > /var/lib/postgresql/data/postgresql.auto.conf
              echo "primary_slot_name = 'replica_slot_0'" >> /var/lib/postgresql/data/postgresql.auto.conf
              touch /var/lib/postgresql/data/standby.signal
              chown postgres:postgres /var/lib/postgresql/data/standby.signal
              cp /etc/postgresql/postgresql-slave.conf /var/lib/postgresql/data/postgresql.conf
              cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
              exec docker-entrypoint.sh postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-auth
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
            - mountPath: /etc/postgresql
              name: postgresql-slave-configmap

        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.17.7
          args: [ "-c", "/etc/filebeat.yml", "-e" ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
              readOnly: true

      volumes:
        - name: postgresql-slave-configmap
          configMap:
            name: postgresql-slave-configmap
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data-slave-0
        - name: filebeat-config
          configMap:
            name: filebeat-postgresql-config