apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      initContainers:
        - name: install-jdbc-driver
          image: curlimages/curl
          command: ['sh', '-c']
          args:
            - |
              curl -L -o /drivers/postgresql-42.7.5.jar https://jdbc.postgresql.org/download/postgresql-42.7.5.jar
              echo "Downloaded JDBC driver successfully"
          volumeMounts:
            - name: jdbc-drivers
              mountPath: /drivers
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.17.7
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service.elk-stack:9200
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch-service.elk-stack:9200
            - name: XPACK_MONITORING_ENABLED
              value: "true"
            - name: XPACK_MONITORING_ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service.elk-stack:9200
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 9600
              name: monitoring
          command:
            - /bin/bash
            - -c
            - |
              cp /jdbc-drivers/* /usr/share/logstash/
              /usr/share/logstash/bin/logstash
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: jdbc-drivers
              mountPath: /jdbc-drivers
            - name: pgbench-results
              mountPath: /pgbench_results
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 9600
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 9600
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-combined-config
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: jdbc-drivers
          emptyDir: {}
        - name: pgbench-results
          emptyDir: {}