apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: elk-stack
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      protocol: TCP
      targetPort: 5044
      name: beats
    - port: 9600
      protocol: TCP
      targetPort: 9600
      name: monitoring