apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-slave-2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi

  