apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-slave-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi

  