apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-backup-script
  namespace: default
data:
  backup.sh: |
    export PGPASSWORD="${MASTER_PASSWORD}"
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="/tmp/postgres_backup_${TIMESTAMP}.dump"
    pg_dump -h postgresql-master -U ${MASTER_USER} -Fc -f ${BACKUP_FILE} ${MASTER_DB}
    
    if [ $? -ne 0 ]; then
      exit 1
    fi

    export PGPASSWORD="${LOCAL_PASSWORD}"
    psql -h localhost -p 5430 -U ${LOCAL_USER} -c "DROP DATABASE IF EXISTS ${LOCAL_DB}_${TIMESTAMP};"
    psql -h localhost -p 5430 -U ${LOCAL_USER} -c "CREATE DATABASE ${LOCAL_DB}_${TIMESTAMP};"
    pg_restore -h localhost -p 5430 -U ${LOCAL_USER} -d ${LOCAL_DB}_${TIMESTAMP} ${BACKUP_FILE}
    
    if [ $? -ne 0 ]; then
      echo "Warning: An error occurred while restoring data, but the process continues."
    fi
    
    OLD_DBS=$(psql -h localhost -p 5430 -U ${LOCAL_USER} -t -c "SELECT datname FROM pg_database WHERE datname LIKE '${LOCAL_DB}_%' ORDER BY datname DESC OFFSET 5;" | tr -d ' ')
    
    for db in $OLD_DBS; do
      psql -h localhost -p 5430 -U ${LOCAL_USER} -c "DROP DATABASE IF EXISTS $db;"
    done
    rm -f ${BACKUP_FILE}
