apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-master
  labels:
    component: postgresql-master
spec:
  selector:
    matchLabels:
      component: postgresql-master
  serviceName: postgresql-master
  template:
    metadata:
      labels:
        component: postgresql-master
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          command:
            - sh
            - -c
            - docker-entrypoint.sh -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-auth
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data-master
            - mountPath: /etc/postgresql
              name: postgresql-master-configmap
      volumes:
        - name: postgresql-master-configmap
          configMap:
            name: postgresql-master-configmap
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data-master
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi