apiVersion: v1
kind: Service
metadata:
  name: postgresql-master
  namespace: default
spec:
  selector:
    component: postgresql-master
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer