apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-patroni-config
  namespace: patroni
data:
  metricbeat.yml: |-
    metricbeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: true

    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          scope: node
          node: ${NODE_NAME}
          hints.enabled: true

    metricbeat.modules:
      - module: postgresql
        enabled: true
        metricsets:
          - database
          - bgwriter
          - activity
          - statement
        period: 10s
        hosts: ["postgresql://localhost:5432/airline_reservation_db?sslmode=disable"]
        username: tuan
        password: ${DB_PASSWORD}

    processors:
      - add_cloud_metadata: ~
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    setup.dashboards.enabled: true
    ssl.verification_mode: "none"
    
    setup.template.enabled: false
    
    setup.ilm.enabled: true
    setup.ilm.rollover_alias: "filebeat"
    setup.ilm.pattern: "{now/d}-000001"
    
    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOST}"]
      index: "metricbeat-%{[agent.version]}"

    setup.kibana:
      host: "${KIBANA_HOST}"
    
    logging.level: info