apiVersion: v1
kind: Service
metadata:
  name: postgresql-slaves
  namespace: default
spec:
  selector:
    component: postgresql-slave
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-replicas
  namespace: default
spec:
  selector:
    component: postgresql-slave
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-slave-0
  namespace: default
spec:
  selector:
    component: postgresql-slave
    statefulset.kubernetes.io/pod-name: postgresql-slave-0
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-slave-1
  namespace: default
spec:
  selector:
    component: postgresql-slave
    statefulset.kubernetes.io/pod-name: postgresql-slave-1
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30433
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-slave-2
  namespace: default
spec:
  selector:
    component: postgresql-slave
    statefulset.kubernetes.io/pod-name: postgresql-slave-2
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30434
  type: NodePort