apiVersion: v1
kind: Service
metadata:
  name: postgresql-slave-proxy
spec:
  selector:
    component: postgresql-slave
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30433
  type: NodePort