apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-patroni-config
  namespace: patroni
data:
  filebeat.yml: |-
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: true
    
    filebeat.modules:
      - module: postgresql
        log:
          enabled: true
          var.paths: ["/var/lib/postgresql/data/pgroot/data/pg_log/*.csv"]
    
    processors:
      - decode_csv_fields:
          fields:
            message: postgresql.csv
          separator: ","
          ignore_missing: false
          overwrite_keys: true
          trim_leading_space: false
          fail_on_error: true
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          kube_config: $Filebeat Reference/.kube/config
          in_cluster: true
          default_indexers.enabled: false
          default_matchers.enabled: false
          indexers:
            - ip_port:
          matchers:
            - fields:
              lookup_fields: ["metricset.host"]
      - drop_fields:
          fields: ["agent", "ecs", "input", "log"]
          ignore_missing: true

    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOST}"]
      data_stream:
        enabled: true
    
    setup.template.enabled: false
    setup.dashboards.enabled: true
    
    setup.ilm.enabled: true
    setup.ilm.rollover_alias: "filebeat"
    setup.ilm.pattern: "{now/d}-000001"
    
    setup.kibana:
      host: "${KIBANA_HOST}"